### PR TITLE
Fixing Linting Issues

### LINKED ISSUE #46: Clean up our linting errors/warnings
@parithon recently added ESLint configurations to the project. Because there were so many errors, he changed them to warnings.

We need to revisit these and clean them up.

This would be an amazing issue to get involved with for Hacktoberfest.

### PR DESCRIPTION
**Pull request by NotMyself**
Fixes #46 

## To Do

- [x] add npm script for lint `--fix` command
- [x] run `npm run lint:fix`
- [x] resolve remaining 22 warnings
- [ ] enable warnings as errors in lint config

### CODE REVIEW

**Comment by NotMyself** [comment]
The remaining 48 lint warnings violate these rules:
- `@typescript-eslint/no-explicit-any`
- `@typescript-eslint/explicit-module-boundary-types`
- `@typescript-eslint/ban-types`

Forgive me, I don't typescript and have no idea what is going on...

selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by parithon** [comment]
Here are the docs where we can get more insight into the rules that are in violation:
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/docs/rules

- [@typescript-eslint/no-explicit-any](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-explicit-any.md)
Using the `any` type defeats the purpose of using TypeScript. When any is used, all compiler type checks around that value are ignored. If a type is truly unknown, we should use the `unknown` type for type safety. [_See_ **Unknown** basic type](https://www.typescriptlang.org/docs/handbook/basic-types.html#unknown)
- [@typescript-eslint/explicit-module-boundary-types](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md)
Explicit types for function return values and arguments make it clear to any calling code what is the module boundary's input and output. (e.g. `function AnswerToLife() { return 42 }` vs. `function AnswerToLife(): number { return 42 }`)
- [@typescript-eslint/ban-types](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md)
Some built-in types have aliases, some types are considered dangerous or harmful. It's often a good idea to ban certain types to help with consistency and safety.
Default banned types:  upper-case primitive types (i.e. `Boolean` vs `boolean`), `Function`, `Object` or `{}`, and `object`

image

**Comment by NotMyself** [comment]
@parithon that helped a bit. Thanks. I was better able to understand what the issue was.

**Comment by MichaelJolley** [comment]
@NotMyself can you ping me when you're ready for a review of this one.

**Comment by NotMyself** [comment]
@MichaelJolley will do.

**Pull request merged**
