### PR TITLE
Updated CONTIBUTING directions to make setup a little easier

### PR DESCRIPTION
**Pull request by RamblingGeekUK**
- Added a link with the required scopes for the Twitch Chat OAuth Password Generator.
- Updated the Fauna DB section with updated directions as it seems the UI has been changed.

### CODE REVIEW

**Review by cmjchrisjones — APPROVED** [review]
Looks OK to me, was able to follow along and get number1 setup and working!

**Comment by MichaelJolley** [comment]
@RamblingGeekUK thanks for helping make the documentation better. It looks like you've got an older version of the codebase. Make sure you're up to date.

**Comment by RamblingGeekUK** [comment]
fixed

**Comment by MichaelJolley** [comment]
@all-contributors please add @RamblingGeekUK for documentation

**Pull request merged**
